#!/bin/sh
if [ `grep -c "nginx" /etc/passwd` = "1" ]; then 
    FASTCGI_USER=nginx
elif [ `grep -c "www-data" /etc/passwd` = "1" ]; then 
    FASTCGI_USER=www-data
elif [ `grep -c "http" /etc/passwd` = "1" ]; then 
    FASTCGI_USER=http
else 
# Configure la variable FASTCGI_USER a continuación para el usuario 
# con el que quiere ejecutar los procesos php-fastcgi

FASTCGI_USER=FACENTOS
fi

/usr/bin/spawn-fcgi -a 127.0.0.1 -p 9000 -C 6 -u $FASTCGI_USER -f /usr/bin/php-cgi
